extensions:
  basicauth/loki:
    client_auth:
      username: admin
      password: admin

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp/loki]