receivers:
  otlp:
    protocols:
      grpc: "http://collector:4317"

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    logs:
      receivers: [otlp]
#      processors: [batch]
      exporters: [loki]